# This is a basic workflow to help you get started with Actions

name: unmaintained-modified-files

# Controls when the action will run. 
on: [ push ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Get the branch name
      # Using the API, find files on the PR
      # for each file, check if each file is part of the XXX.txt file
      - name: Extract Pull request name
        run: echo running on branch $${{ github.event.pull_request.number }}
      - name: list files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: github
        run: |          
          FILES=$(curl -s -H "Authorization: token ${{github.token}}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
          echo $FILES
        
