# This is a workflow to check the serviceowners of the files modified in a PR
# It failed when the PR contains some files without serviceowners
name: Check serviceowners for modified files in the PR

on: 
  # Triggers the workflow on pull request events
  pull_request:
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get files from the PR
        id: get_files
        run: |
          API_URL="https://api.github.com/repos/jchuerva/test_app_1/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.TOKEN }}" $API_URL | jq -r '.[] | .filename')
          for file in $FILES
          do
            if grep -Fxq "$file" docs/serviceowners_no_matches.txt
            then
              UNOWNED_FILES+=($file)
            fi
          done
          if [ $UNOWNED_FILES ]
          then
            FAILED_MESSAGE=" \
            This file currently does not belong to a service. To fix this, please do one of the following:%0A \
            %0A \
              * Find a service that makes sense for this file and update SERVICEOWNERS accordingly%0A \
              * Create a new unowned service and assign this file to it%0A \
            %0A \
            Learn more about service maintainership here:%0A \
            https://thehub.github.com/engineering/development-and-ops/dotcom/serviceowners \
            "
            echo "This PR touch some unowned files"
            for file in $UNOWNED_FILES
            do
              echo "   - $file"
              echo "::warning file=$file::${FAILED_MESSAGE}"
            done
            echo "To fix it, you need to find a maintainer for them and update SERVICEOWNERS."
            echo "If you assign them to other team, please let them know it."
            echo "Learn more in:"
            echo "https://thehub.github.com/engineering/development-and-ops/dotcom/serviceowners/"
            echo ""
            exit 1
          else
            echo "Looks good! All files has an owner!"
          fi