# This is a workflow to check the serviceowners of the files modified in a PR
# It failed when the PR contains some files without serviceowners
name: Check serviceowners for modified files in the PR

on: 
  # Triggers the workflow on pull request events
  pull_request:
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get files from the PR
        id: get_files
        run: .github/workflows/main.sh
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}