# This is a workflow to check the serviceowners of the files modified in a PR
# It failed when the PR contains some files without serviceowners
name: Check owner of modified files

  # Allows you to run this workflow manually from the Actions tab and in every pull_request
on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Get ownership of files modified
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: github/github
        run: |
          gem install octokit
          ruby .github/workflows/check_unmaintained_files.rb